
on: [push]

jobs:
  ofm-check-job:
    name: Check OFM

    uses: openknx/actions/.github/workflows/openknx-ofm-check.yml@v0
    with:
      # ofm: OFM-InternetWeatherModule
      # ofm: ${{ github.event.repository.name }}
      # Note: use ${{ github.ref_name }} from OFM-repo
      # ofm_ref: ${{ github.ref_name }}
      ofm_prefix: IW
      oam: OAM-InternetServices
      # oam_ref: v1dev
      # knxprod_xml: InternetServices-Release
      target: Release
      KNXPROD_PREFIX: InternetServices
